ci

diff --git a/philosophy-reading-list/Makefile b/philosophy-reading-list/Makefile
--- a/philosophy-reading-list/Makefile
+++ b/philosophy-reading-list/Makefile
@@ -15,9 +15,19 @@ export TEXINPUTS := .//:./style//:./tex//:${TEXINPUTS}
 OUTPUT := $(shell cat meta.yaml | grep output | awk '{split($$0,a,":"); print a[2]}' | xargs)
 DOREFS := $(filter $(shell cat meta.yaml | grep ^dorefs | awk '{split($$0,a,":"); print a[2]}' | xargs),true)
 
-OPS_FULLPDF := $(if $(DOREFS),templates/refs_tex.md templates/backmatter.md,templates/backmatter.md)
-OPS_FULLHTML := $(if $(DOREFS),templates/refs.md templates/backmatter.md,templates/backmatter.md)
-OPS_SECTION := $(if $(DOREFS),templates/refs_subsection.md templates/backmatter.md,templates/backmatter.md)
+ifeq ($(DOREFS), true)
+HTML_DEPS := bibs/mybib.bib
+PDF_DEPS := bibs/mybib.bib
+OPS_FULLPDF := templates/refs_tex.md templates/backmatter.md
+OPS_FULLHTML := templates/refs.md templates/backmatter.md
+OPS_SECTION := templates/refs_subsection.md templates/backmatter.md
+else
+HTML_DEPS := 
+PDF_DEPS := 
+OPS_FULLPDF := templates/backmatter.md
+OPS_FULLHTML := templates/backmatter.md
+OPS_SECTION := templates/backmatter.md
+endif
 
 
 ##-----------------------------------------------------------------------------
@@ -31,7 +41,8 @@ MD_FILES := $(filter-out README.md, $(wildcard *.md))
 MD_FILES := $(filter-out index.md, $(MD_FILES))
 HTML_FILES := $(MD_FILES:%.md=%.html)
 PDF_FILES := $(MD_FILES:%.md=%.pdf)
-MD_FILES_WITH_REFS := $(shell egrep -l '@' *.md)
+BIB_TXT_FILES := $(wildcard bibs/*.txt)
+#MD_FILES_WITH_REFS := $(shell egrep -l '@' *.md)
 
 
 ## MD_FILES   =  chap1.md   chap2.md   ...
@@ -43,14 +54,14 @@ MD_FILES_WITH_REFS := $(shell egrep -l '@' *.md)
 ## targets
 ##-----------------------------------------------------------------------------
 
-default: pdf
+default: html
 
 all: html pdf
 
 html: $(HTML_FILES) index.html
 	$(PRINT) "html done."
 
-pdf: $(OUTPUT).pdf
+pdf: $(OUTPUT).pdf wordcount/wc.csv
 
 index.md: $(MD_FILES)
 	@if [ -f index.txt ]; \
@@ -73,7 +84,7 @@ index.html: index.md meta.yaml
 		-o $@ $< meta.yaml
 	$(PRINT) "make $@ done."
 
-$(OUTPUT).html: $(MD_FILES) mybib.bib meta.yaml
+$(OUTPUT).html: $(MD_FILES) $(HTML_DEPS) meta.yaml
 	@pandoc \
 		-t html \
 		--ascii \
@@ -84,14 +95,14 @@ $(OUTPUT).html: $(MD_FILES) mybib.bib meta.yaml
 		--variable=css:templates/markdown-memo.css \
 		--template=./templates/index_template.html \
 		--mathjax \
-		--bibliography=mybib.bib \
+		--bibliography=bibs/mybib.bib \
 		--filter pandoc-crossref \
 		--filter pandoc-citeproc \
 		-o $@ $(MD_FILES) $(OPS_FULLHTML) meta.yaml
 	$(PRINT) "make $@ done."
 
 ## create html
-%.html: %.md mybib.bib meta.yaml
+%.html: %.md $(HTML_DEPS) meta.yaml
 	@pandoc \
 		-t html \
 		--ascii \
@@ -105,130 +116,181 @@ $(OUTPUT).html: $(MD_FILES) mybib.bib meta.yaml
 	@echo `cat $@.tmp | grep -E "<title.*>(.*?)</title>" | sed 's/<title.*>\(.*\)<\/title>/doc_title: "\1"/'` >> meta.yaml.tmp
 	@echo `cat $@.tmp | grep -E "<h1.*>(.*?)</h1>" | head -n1 | sed 's/<h1.*>\(.*\)<\/h1>/page_title: "\1"/'` >> meta.yaml.tmp
 	@echo '...\n' >> meta.yaml.tmp
-	@pandoc \
-		-t html \
-		--ascii \
-		--standalone \
-		--smart \
-		--variable=date-meta:"$(DATE)" \
-		--variable=css:templates/markdown-memo.css \
-		--template=./templates/outline_template.html \
-		--mathjax \
-		--bibliography=mybib.bib \
-		--filter pandoc-crossref \
-		--filter pandoc-citeproc \
-		-o $@ $< $(OPS_SECTION) meta.yaml.tmp
+	@if [ "$(DOREFS)" = "true" ] && grep --quiet @ $< ; \
+	then \
+		pandoc \
+			-t html \
+			--ascii \
+			--standalone \
+			--smart \
+			--variable=date-meta:"$(DATE)" \
+			--variable=css:templates/markdown-memo.css \
+			--template=./templates/outline_template.html \
+			--mathjax \
+			--bibliography=bibs/mybib.bib \
+			--filter pandoc-crossref \
+			--filter pandoc-citeproc \
+			-o $@ $< $(OPS_SECTION) meta.yaml.tmp ; \
+	else \
+		pandoc \
+			-t html \
+			--ascii \
+			--standalone \
+			--smart \
+			--variable=date-meta:"$(DATE)" \
+			--variable=css:templates/markdown-memo.css \
+			--template=./templates/outline_template.html \
+			--mathjax \
+			--filter pandoc-crossref \
+			-o $@ $< templates/backmatter.md meta.yaml.tmp ; \
+	fi
 	@rm -f meta.yaml.tmp $@.tmp
 	$(PRINT) "make $@ done."
 
 ## create the full pdf 
-#$(OUTPUT).pdf: $(MD_FILES) mybib.bib meta.yaml
-#	pandoc \
+#$(OUTPUT).pdf: $(MD_FILES) $(PDF_DEPS) meta.yaml
+#	@pandoc \
 #		--standalone \
 #		--smart \
 #		--variable=date-meta:"$(DATE)" \
 #		--template=templates/default_template.tex \
 #		--filter pandoc-crossref \
 #		--filter pandoc-eqnos \
-#		--bibliography=mybib.bib \
+#		--bibliography=bibs/mybib.bib \
 #		--filter pandoc-citeproc \
 #		-o $(OUTPUT).pdf $(MD_FILES) $(OPS_FULLPDF) meta.yaml
 #	$(PRINT) "make $@ done."
 
-# create the full pdf via pandoc to tex then pdflatex
+## create the full pdf via pandoc to tex then pdflatex
 $(OUTPUT).pdf: $(OUTPUT).tex
 	@pdflatex -interaction=nonstopmode $< &> latex.log
 	@pdflatex -interaction=nonstopmode $< &> latex.log
 	$(PRINT) "make $@ done."
 
 ## create the pdf for a section
-%.pdf: %.md mybib.bib meta.yaml
-	@pandoc \
-		--standalone \
-		--smart \
-		--variable=date-meta:"$(DATE)" \
-		--template=templates/default_template.tex \
-		--filter pandoc-crossref \
-		--filter pandoc-eqnos \
-		--bibliography=mybib.bib \
-		--filter pandoc-citeproc \
-		-o $@ $< $(OPS_SECTION) meta.yaml
-	$(PRINT) "make $@ done."
-
-## create md with references replaced and bibliography created
-$(OUTPUT).mds: $(MD_FILES) mybib.bib meta.yaml
-	@pandoc \
-		-t markdown_github \
-		--standalone \
-		--smart \
-		--bibliography=mybib.bib \
-		--filter pandoc-citeproc \
-		-o $@.tmp $(MD_FILES) $(OPS_FULLHTML) meta.yaml
-	@cat $@.tmp | sed -E 's/\[([0-9][0-9]?[0-9]?)\]/\[\^\1\]/g' | sed -E 's/^\[\^([0-9][0-9]?[0-9]?)\]\ /\[\^\1\]:\ /' > $@
-	@rm -f $@.tmp
-	$(PRINT) "make $@ done."
-
-%.mds: %.md mybib.bib meta.yaml
-	@pandoc \
-		-t markdown_github \
-		--standalone \
-		--smart \
-		--bibliography=mybib.bib \
-		--filter pandoc-citeproc \
-		-o $@.tmp $< $(OPS_SECTION) meta.yaml
-	@cat $@.tmp | sed -E 's/\[([0-9][0-9]?[0-9]?)\]/\[\^\1\]/g' | sed -E 's/^\[\^([0-9][0-9]?[0-9]?)\]\ /\[\^\1\]:\ /' > $@
-	@rm -f $@.tmp
-	$(PRINT) "make $@ done."
-
-## create html from mds
-%.htmls: %.mds
-	@pandoc \
-		-t html \
-		--ascii \
-		--standalone \
-		--smart \
-		--variable=date-meta:"$(DATE)" \
-		--variable=css:templates/markdown-memo.css \
-		--template=./templates/outline_template.html \
-		-o $@ $< meta.yaml
-	$(PRINT) "make $@ done."
+#%.pdf: %.md $(PDF_DEPS) meta.yaml
+#	@pandoc \
+#		--standalone \
+#		--smart \
+#		--variable=date-meta:"$(DATE)" \
+#		--template=templates/default_template.tex \
+#		--filter pandoc-crossref \
+#		--filter pandoc-eqnos \
+#		--bibliography=bibs/mybib.bib \
+#		--filter pandoc-citeproc \
+#		-o $@ $< $(OPS_SECTION) meta.yaml
+#	$(PRINT) "make $@ done."
 
 ## create tex with references replaced and bibliography created
-$(OUTPUT).tex: $(MD_FILES) mybib.bib meta.yaml
-	@pandoc \
-		-t latex \
-		--ascii \
-		--standalone \
-		--smart \
-		--template=templates/default_template.tex \
-		--filter pandoc-crossref \
-		--bibliography=mybib.bib \
-		--filter pandoc-citeproc \
-		-o $@ $(MD_FILES) $(OPS_FULLPDF) meta.yaml
+$(OUTPUT).tex: $(MD_FILES) $(PDF_DEPS) meta.yaml
+	@if [ "$(DOREFS)" = "true" ] ; \
+	then \
+		pandoc \
+			-t latex \
+			--ascii \
+			--standalone \
+			--smart \
+			--template=templates/default_template.tex \
+			--filter pandoc-crossref \
+			--bibliography=bibs/mybib.bib \
+			--filter pandoc-citeproc \
+			-o $@ $(MD_FILES) $(OPS_FULLPDF) meta.yaml ; \
+	else \
+		pandoc \
+			-t latex \
+			--ascii \
+			--standalone \
+			--smart \
+			--template=templates/default_template.tex \
+			--filter pandoc-crossref \
+			-o $@ $(MD_FILES) $(OPS_FULLPDF) meta.yaml ; \
+	fi
 	@python templates/transform_tex.py $@
 	$(PRINT) "make $@ done."
 
-%.tex: %.md mybib.bib meta.yaml
-	@pandoc \
-		-t latex \
-		--ascii \
-		--standalone \
-		--smart \
-		--template=templates/default_template.tex \
-		--filter pandoc-crossref \
-		--bibliography=mybib.bib \
-		--filter pandoc-citeproc \
-		-o $@ $< $(OPS_SECTION) meta.yaml
-	@python templates/transform_tex.py $@
+## create the tex for a section
+#%.tex: %.md $(PDF_DEPS) meta.yaml
+#	@pandoc \
+#		-t latex \
+#		--ascii \
+#		--standalone \
+#		--smart \
+#		--template=templates/default_template.tex \
+#		--filter pandoc-crossref \
+#		--bibliography=bibs/mybib.bib \
+#		--filter pandoc-citeproc \
+#		-o $@ $< $(OPS_SECTION) meta.yaml
+#	@python templates/transform_tex.py $@
+#	$(PRINT) "make $@ done."
+
+bibs/mybib.bib: $(BIB_TXT_FILES)
+	@if [[ -z "$(BIB_TXT_FILES)" ]] ; \
+	then \
+		echo "==>   ERROR: No bibliography files found in bibs/. Set dorefs=false in meta.yaml." ; \
+		exit 1 ; \
+	else \
+		python templates/markdown2bib.py --out=bibs/mybib.bib $(BIB_TXT_FILES) ; \
+	fi
 	$(PRINT) "make $@ done."
 
-mybib.bib: $(MD_FILES)
-	@cat bibs/*.bib > mybib.bib
+wordcount/wc.csv: $(MD_FILES) $(OUTPUT).pdf
+	@if [ ! -d wordcount ]; \
+	then \
+		mkdir wordcount ; \
+	fi
+	@if [ ! -f $@ ]; \
+	then \
+		printf "%s,%s,%s\n" "Date" "Words" "Pages" >> $@ ; \
+	fi
+	@printf "%16s, %8i, %5i\n" `date +"%Y-%m-%d-%Hh%M"` `cat $(MD_FILES) | wc | awk '{split($$0,a," "); print a[1]}'` `pdfinfo $(OUTPUT).pdf | grep Pages | tr -d "Pages: "` >> $@
+	@cd wordcount/ ; python ../templates/wordcount.py wc.csv ; cd ..
 	$(PRINT) "make $@ done."
 
+
+##-----------------------------------------------------------------------------
+## create md with references replaced and bibliography created
+#$(OUTPUT).mds: $(MD_FILES) $(HTML_DEPS) meta.yaml
+#	@pandoc \
+#		-t markdown_github \
+#		--standalone \
+#		--smart \
+#		--bibliography=bibs/mybib.bib \
+#		--filter pandoc-citeproc \
+#		-o $@.tmp $(MD_FILES) $(OPS_FULLHTML) meta.yaml
+#	@cat $@.tmp | sed -E 's/\[([0-9][0-9]?[0-9]?)\]/\[\^\1\]/g' | sed -E 's/^\[\^([0-9][0-9]?[0-9]?)\]\ /\[\^\1\]:\ /' > $@
+#	@rm -f $@.tmp
+#	$(PRINT) "make $@ done."
+#
+#%.mds: %.md $(HTML_DEPS) meta.yaml
+#	@pandoc \
+#		-t markdown_github \
+#		--standalone \
+#		--smart \
+#		--bibliography=bibs/mybib.bib \
+#		--filter pandoc-citeproc \
+#		-o $@.tmp $< $(OPS_SECTION) meta.yaml
+#	@cat $@.tmp | sed -E 's/\[([0-9][0-9]?[0-9]?)\]/\[\^\1\]/g' | sed -E 's/^\[\^([0-9][0-9]?[0-9]?)\]\ /\[\^\1\]:\ /' > $@
+#	@rm -f $@.tmp
+#	$(PRINT) "make $@ done."
+#
+### create html from mds
+#%.htmls: %.mds
+#	@pandoc \
+#		-t html \
+#		--ascii \
+#		--standalone \
+#		--smart \
+#		--variable=date-meta:"$(DATE)" \
+#		--variable=css:templates/markdown-memo.css \
+#		--template=./templates/outline_template.html \
+#		-o $@ $< meta.yaml
+#	$(PRINT) "make $@ done."
+
+
+##-----------------------------------------------------------------------------
 # JUNK = *.aux *.log *.bbl *.blg *.brf *.cb *.ind *.idx *.ilg *.inx *.dvi *.toc *.out *~ ~* spellTmp *.lot *.lof *.ps *.d
-JUNK = *.mds *.htmls *.tex *.aux *.dvi *.fdb_latexmk *.fls *.log *.out *.toc *.bib *.tmp *-tmp.html index.md
-OUTS = *.html *.pdf
+JUNK = *.mds *.htmls *.tex *.aux *.dvi *.fdb_latexmk *.fls *.log *.out *.toc *.tmp *-tmp.html index.md
+OUTS = *.html *.pdf bibs/*.bib
 
 clean:
 	@rm -f $(JUNK)
@@ -239,4 +301,5 @@ realclean: clean
 	$(PRINT) "make $@ done."
 
 over: realclean default
+
 
